version: "3.0"

services:
  # mariadb:
  #   # Pinning MariaDB to point release 10.4.30 works around the issues with the
  #   # database migrations seen with 10.4.31 in issue #1212.
  #   #
  #   # TODO: Get database migrations to work with the latest point releases of
  #   # MariaDB 10.4.
  #   image: mariadb:10.4.30
  #   ports:
  #     - 33306:3306
  #   networks:
  #     - default
  #     - mega-net
  #   environment:
  #     MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  #     MYSQL_DATABASE: stevedb
  #     MYSQL_USER: steve
  #     MYSQL_PASSWORD: YouCantGuessThisIs@Mimi
  #   volumes:
  #     - mariadbdata:/var/lib/mysql
  #   restart: unless-stopped

  mysqldb:
    image: mysql:8.0
    container_name: steve-db
    tty: true
    ports:
      - 13306:3306
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "1231231"
      MYSQL_DATABASE: stevedb
      MYSQL_USER: steve
      MYSQL_PASSWORD: YouCantGuessThisIs@Mimi
    volumes:
      - ./docker/mysql:/etc/mysql/conf.d
      - mysqldata:/var/lib/mysql

  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: joehe/ocpp-steve-server:3.6.06
    tty: true
    # image: steve-app
    container_name: steve-app
    ports:
      - 18180:8180
    networks:
      - default
    volumes:
      - ./:/code
    links:
      - mysqldb:mariadb

networks:
  default:
    name: steve-docker_default

volumes:
  # mariadbdata:
  mysqldata:
