name: "steve"

services:
  fusquare-mysql:
    image: mysql:8.2
    container_name: fusquare-mysql
    tty: true
    ports:
      - 13306:3306
    networks:
      - fusquare-net
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: stevedb
      MYSQL_USER: steve
      MYSQL_PASSWORD: YouCantGuessThisIs@Mimi
    volumes:
      - ./docker/mysql:/etc/mysql/conf.d
      - fusquare-mysql:/var/lib/mysql

  fusquare-steve:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    image: fusquare-steve
    container_name: fusquare-steve
    ports:
      - 18180:8180
    networks:
      - fusquare-net
    links:
      - fusquare-mysql:mariadb

networks:
  fusquare-net:

volumes:
  fusquare-mysql:
